### ISSUE TITLE
Cannot use service account 

### ISSUE THREAD

**Issue by morgante** [DeviaVir/terraform-provider-gsuite#11]
I'm trying to use #9 to run this provider as a service account but am running into an error with my config.

This is my config:

```hcl
provider "gsuite" {
  credentials             = "${path.module}/sa-key.json"
  impersonated_user_email = "${var.admin_email}"
}
```

When I try to run this, I get the following error:

```
Error: provider.gsuite: : invalid or unknown key: credentials
Error: provider.gsuite: : invalid or unknown key: impersonated_user_email
```

Note: this is even after following the dev instructions to make a local build from master. Can you help me resolve this, or do a new release with the service account functionality included?

**Comment by morgante** [comment]
It looks like the issue was with me using an old version of Terraform.

**Comment by DeviaVir** [comment]
I think specifically in the folder containing your `.tf` files you can force a refresh by re-initing:
```
rm -rf .terraform
terraform init
```
