### ISSUE TITLE
Credentials input file

### ISSUE THREAD

**Issue by Claywd** [DeviaVir/terraform-provider-gsuite#110]
Would be nice if we could supply these inputs as a data module instead of a pure json file available on disk. 

Use case: Team A sops encrypts their service account credentials in the tf code repo. Sops tf provider is used to decrypt that file into memory as a data module. Only the service account in the TF runtime and Team A can decrypt the secrets. Team B-Z is welcome to use whatever pipeline and sops file without access to infra sensitive credentials. 

Creds are never stored decrypted on disk but always in memory and the credentials + KMs used to access decrypt file are stored in an Environment Variable and probably from a completely different cloud provider. :) 

Distributed security FTW

Happy to contribute to this as well if we can get it marked as a feature.

**Comment by DeviaVir** [comment]
Does this duplicate https://github.com/DeviaVir/terraform-provider-gsuite/issues/70 ?

**Comment by Claywd** [comment]
> Does this duplicate #70 ?

ish. They want to supply a token for the gsuite provider to use, I'm suggesting to supply the whole file as a variable. Without looking at the codebase, I would think my suggestion is easier to implement since you just point whatever function scrapes that file at a json variable in memory instead of trying to create what you need from individual variables. 

Ultimately I think it depends on what you need for auth. Do you need the whole file or just the private_key_id and private_key? If its the former, then what I'm suggesting is better and if its the later then individual variables (that also support ENV vars) would serve better long term.

**Comment by Claywd** [comment]
After reading #70 and learning about access tokens I am closing this in favor of #70 . I will contribute there.
