### ISSUE TITLE
Missing argument Name on user creation

### ISSUE THREAD

**Issue by alibabjo** [DeviaVir/terraform-provider-gsuite#113]
Hello,
I'm trying to create gsuite user, but systematically having the same issue :

Error: Missing required argument
  on user.tf line 16, in resource "gsuite_user" "developer":
  16: resource "gsuite_user" "developer" {
The argument "name" is required, but no definition was found.
Error: Unsupported block type

here is my user data : 
resource "gsuite_user" "developer" {
  name {
    family_name = "testjha"
    given_name  = "jhatest"
  }
  password = "testtest123!"
  primary_email = "developer@xx.xxx"
}

any idea?

thk in advance
Regard

**Comment by DeviaVir** [comment]
What version of terraform are you using? Do you see the same error when you use:
```
name = {
  family_name = "testjha"
  given_name = "jhatest"
}
```

**Comment by alibabjo** [comment]
i'm using v0.1.35 of Gsuite provider.
with the above format , i've this error: 

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by alibabjo** [comment]
oups sorry, i've provide gsuite provider version..
I currently use terraform_0.12.15_linux_amd64.

**Comment by alibabjo** [comment]
Hello,
solved....
You are right the good format is :
name = {
  family_name = "testjha"
  given_name = "jhatest"
}


but i have also forget to add the corresponding service account right on cloud identity ( user scope)....
Maybe the error should be "permission denied" ?
