### ISSUE TITLE
error creating group member:

### ISSUE THREAD

**Issue by aaronstrong** [DeviaVir/terraform-provider-gsuite#115]
Getting the below error when using the GCP Project Factory version 5.1.1 with google provider 2.20 and gsuite provider  0.1.35. Project gets created, but errors when creating the G Suite group. Using a service account that has G Suite domain-wide delegation. I've also issued the APIs access for users and group management. I've tried both key formats of .json and .p12

Error: error creating group member: Post https://www.googleapis.com/admin/directory/v1/groups/<group_name%40<domain.com>/members?alt=json&prettyPrint=false: private key should be a PEM or plain PKCS1 or PKCS8; parse error: asn1: syntax error: sequence truncated

  on .terraform/modules/project-factory/terraform-google-modules-terraform-google-project-factory-46e55ae/modules/gsuite_enabled/main.tf line 24, in resource "gsuite_group_member" "service_account_sa_group_member":
  24: resource "gsuite_group_member" "service_account_sa_group_member" {

**Comment by DeviaVir** [comment]
How does your `provider "gsuite" {}` look like?

**Comment by gtmtech** [comment]
Am getting this too @aaronstrong - how did you solve it?
