### ISSUE TITLE
Building dist files

### ISSUE THREAD

**Issue by zamir0109** [DeviaVir/terraform-provider-gsuite#12]
Hi everybody,

I'm trying to create the dist packages from the current branch, however I'm getting this errors when I perform `make dist `command:

> gsuite/config.go:12:2: cannot find package "golang.org/x/oauth2/google" in any of:
>         /go/src/github.com/DeviaVir/terraform-provider-gsuite/vendor/golang.org/x/oauth2/google (vendor tree)
>         /usr/local/go/src/golang.org/x/oauth2/google (from $GOROOT)
>         /go/src/golang.org/x/oauth2/google (from $GOPATH)
> gsuite/config.go:15:2: cannot find package "golang.org/x/oauth2/jwt" in any of:
>         /go/src/github.com/DeviaVir/terraform-provider-gsuite/vendor/golang.org/x/oauth2/jwt (vendor tree)
>         /usr/local/go/src/golang.org/x/oauth2/jwt (from $GOROOT)
>         /go/src/golang.org/x/oauth2/jwt (from $GOPATH)
> gsuite/config.go:13:2: cannot find package "google.golang.org/api/admin/directory/v1" in any of:
>         /go/src/github.com/DeviaVir/terraform-provider-gsuite/vendor/google.golang.org/api/admin/directory/v1 (vendor tree)
>         /usr/local/go/src/google.golang.org/api/admin/directory/v1 (from $GOROOT)
>         /go/src/google.golang.org/api/admin/directory/v1 (from $GOPATH)
> gsuite/resource_group_members.go:9:2: cannot find package "google.golang.org/api/googleapi" in any of:
>         /go/src/github.com/DeviaVir/terraform-provider-gsuite/vendor/google.golang.org/api/googleapi (vendor tree)
>         /usr/local/go/src/google.golang.org/api/googleapi (from $GOROOT)
>         /go/src/google.golang.org/api/googleapi (from $GOPATH)

I'm really sure that I have set the GOPATH, GOROOT, GOBIN variables because performing a `make dev` command everything's go well.

Could you please help me with this, or fix it if there's an issue, or maybe make a release with the current master branch?

Thanks in advance!

**Comment by DeviaVir** [comment]
https://github.com/DeviaVir/terraform-provider-gsuite/releases/tag/v0.1.1
