### ISSUE TITLE
Enable Admin Directory API?

### ISSUE THREAD

**Issue by ademariag** [DeviaVir/terraform-provider-gsuite#127]
Hello,

I am trying to work with a very simple setup, but I am unable to continue because of this error:

```
Error: [ERROR] Error creating group: googleapi: Error 403: Access Not Configured. Admin Directory API has not been used in project 764086051850 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/admin.googleapis.com/overview?project=764086051850 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured
```

Strangely, the link doesn't work, and even more strangely, we do not have a project with id: 764086051850

Do you know what I need to do to enable the api?

**Comment by DeviaVir** [comment]
What authentication mechanism are you using? Is it a service account? Make sure that wherever you created the service account has the admin API enabled.

**Comment by ademariag** [comment]
It was my fault, I was using the personal administrator setup and I had not used a client-id-key. Happy to close.
