### ISSUE TITLE
Allow ignoring duplicate created groups

### ISSUE THREAD

**Issue by mattcary** [DeviaVir/terraform-provider-gsuite#129]
I would find it useful to ignore duplicate groups on creation. For example, if anything has been created outside of terraform.

I have a pull request which I'll send which explains the details.

Thanks.

**Comment by DeviaVir** [comment]
Usually this is resolved by running an import. I thought we made the provider authoritative so that when a group already exists it would just read and overwrite. Is that not the case?

**Comment by mattcary** [comment]
I'm embarrassed to say that I didn't know about terraform import. 

It works fine. It's convenient that one can use the email to import rather than digging around for the id.

Thanks!
