### ISSUE TITLE
Add gsuite provider to Terraform community providers list

### ISSUE THREAD

**Issue by psalaberria002** [DeviaVir/terraform-provider-gsuite#13]
See https://docs.google.com/forms/d/e/1FAIpQLSeenG02tGEmz7pntIqMKlp5kY53f8AV5u88wJ_H1pJc2CmvKA/viewform#responses

**Comment by DeviaVir** [comment]
:+1: done

**Comment by DeviaVir** [comment]
looks like it's listed: https://www.terraform.io/docs/providers/type/community-index.html

So we can close this 💯
