### ISSUE TITLE
Allow adding emails of other domains to G Suite Groups

### ISSUE THREAD

**Issue by nekobrain** [DeviaVir/terraform-provider-gsuite#137]
Hi,

I have tried to add an email with a domain that's not tied to our G Suite to a Google Group but it fails with

> Error: [ERROR] Error updating memberships: [ERROR] Error updating groupMember: googleapi: Error 400: Missing required field: memberKey, required, _redacted_

If I try and add a domain user, though, everything works fine. Is this expected behaviour?

Thanks again for your work!

**Comment by DeviaVir** [comment]
Hey @nekobrain, can you share the terraform code you used?

**Comment by nekobrain** [comment]
Hi @DeviaVir,

sure, here it is:

```
resource "gsuite_group_members" "my_group" {
  group_email = "group@mydomain.com"

  member {
    email = "external_user1@gmail.com"
    role = "MEMBER"
  }

  member {
    email = "external_user2@externaldomain.com"
    role = "MEMBER"
  }                                                                                                                                                                                                                                    

  member {
    email = "external_user3@externaldomain.com"
    role  = "MEMBER"
  }

  member {
    email = "external_user4@externaldomain.com"
    role = "MEMBER"
  }

  member {
    email = "internal_user1@mydomain.com"
    role = "MEMBER"
  }

  member {
    email = "internal_user2@mydomain.com"
    role = "OWNER"
  }
}

```

What I was trying to do was adding `external_user4@externaldomain.com`, but it would fail with the aformentioned error.

**Comment by DeviaVir** [comment]
So I know this is really not that well documented, but what I think needs to happen here is allowing "external members" in the group settings (we have the source for that here: https://github.com/DeviaVir/terraform-provider-gsuite/blob/master/gsuite/resource_group_settings.go#L46-L50)

It lives here in the examples: https://github.com/DeviaVir/terraform-provider-gsuite/blob/master/examples/group-settings/devteam.tf#L14

Make sure to add this scope to your oauth/service account: `https://www.googleapis.com/auth/apps.groups.settings`
