### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by psalaberria002** [DeviaVir/terraform-provider-gsuite#14]
Could you upload new releases to Github?

I am planning to download the binaries for specific versions, and I would prefer not to build it myself.

Thank you.

**Comment by DeviaVir** [comment]
I think this duplicates https://github.com/DeviaVir/terraform-provider-gsuite/issues/12

**Comment by DeviaVir** [comment]
https://github.com/DeviaVir/terraform-provider-gsuite/releases/tag/v0.1.1
