### ISSUE TITLE
Creating group with aliases in single plan fails

### ISSUE THREAD

**Issue by dortort** [DeviaVir/terraform-provider-gsuite#142]
Creating a group with aliases often causes:
```
Error: rpc error: code = Unavailable desc = transport is closing
```
or at times, will stall at `Still creating...` and finally return the error:
```
Error: [ERROR] Error creating group: googleapi: Error 409: Entity already exists., duplicate
```

Creating the group without aliases in one "apply" and then adding the aliases in a following "apply" succeeds.

**Comment by DeviaVir** [comment]
Hi @dortort - thank you for reporting this issue.

Can you try if you still have this issue with this branch? https://github.com/DeviaVir/terraform-provider-gsuite/pull/143

You can run `make dev` from that branch, which will install into your ~/.terraform.d

**Comment by DeviaVir** [comment]
Closing, including this in release `0.1.48` - feel free to reopen if this is still an issue in that release.

**Comment by dortort** [comment]
I've tried with v0.1.50 and still encountered the issue.
![image](https://user-images.githubusercontent.com/1169721/84724754-eeffa100-af56-11ea-9571-def32affc723.png)

**Comment by DeviaVir** [comment]
That's an interesting error. Do you mind trying with `0.1.52`? I was not able to reproduce that error but I was able to create a group with aliases in a single apply using that version.

**Comment by dortort** [comment]
I'll try.
Here's the snippet I'm using, BTW:
```
resource "gsuite_group" "simple_forward" {
  count = length(var.email_forwards)

  name    = var.email_forwards[count.index].name
  email   = var.email_forwards[count.index].email
  aliases = lookup(var.email_forwards[count.index], "aliases", [])
}

resource "gsuite_group_member" "simple_forward" {
  count = length(var.email_forwards)

  group = var.email_forwards[count.index].email
  email = var.email_forwards[count.index].forward_to
}
```

Perhaps the issue is related to the use of a loop?
