### ISSUE TITLE
Please republish for arm64 (new macbook pro M1)

### ISSUE THREAD

**Issue by gtmtech** [DeviaVir/terraform-provider-gsuite#167]
Now golang has reached 1.16 GA, it has support for arm64, so all that should need to be done is to use latest go and republish for all platforms including darwin.arm64 and linux.arm64

Would be lovely to use this on the new macbook pros without having to recompile it locally 

Thanks!

**Comment by gtmtech** [comment]
I have a mac silicon so if you need both a darwin-arm64 and a linux-arm64 image so I am happy to help out if its useful @DeviaVir - I'm going to publish the assets to a forked repo

**Comment by DeviaVir** [comment]
let me know if this works for your arch:
https://github.com/DeviaVir/terraform-provider-gsuite/releases/tag/v0.1.59
