### ISSUE TITLE
Gsuite Group "member" should be able to be type of gsuite group.

### ISSUE THREAD

**Issue by BenKletzine** [DeviaVir/terraform-provider-gsuite#18]
It would be nice to be able to define a member of a gsuite group as a gsuite group.

For example CompanyDevTeams group would consist of DevTeamOne and DevTeamTwo etc.

My use case is to use these in GCP IAM configuration files. Instead of defining a broader group with all the members again, the group could be defined in terms of multiple gsuite groups.

**Comment by DeviaVir** [comment]
Did you close this because you could make your use case work, or for another reason?

**Comment by BenKletzine** [comment]
Since we have an email group associated we each dev team, I think specifying the member email as the group email will work for what I need.
