### ISSUE TITLE
Use specific versions for dependencies

### ISSUE THREAD

**Issue by psalaberria002** [DeviaVir/terraform-provider-gsuite#21]
Grabbing the latest from master seems dangerous. We should probably get the latest stable versions for the google api and the oauth2 library.

**Comment by DeviaVir** [comment]
I'm actually not sure how to pin to a specific version on golang.org, anyone have hints on how to achieve this?

**Comment by mathyourlife-fitbit** [comment]
both golang.org/x/oauth2 and google.golang.org/api repos don't use versioning tags in their git repos.  The Gopkg.toml could be pinned to a specific commit hash if desired.

```
[[constraint]]
  name = "golang.org/x/oauth2"
  revision = "a032972e28060ca4f5644acffae3dfc268cc09db"

[[constraint]]
  name = "google.golang.org/api"
  revision = "4c1b07210d562506ab52117997c3b7e294627ac9"
```

and then update as needed.
