### ISSUE TITLE
Cannot add appengine service account as a member

### ISSUE THREAD

**Issue by BenKletzine** [DeviaVir/terraform-provider-gsuite#23]
Trying to add an appengine service account as member to a gsuite group, as in abc@abc.iam.gserviceaccount.com this returns a 400. However using the gsuite api, this correctly adds the service account to the group. Could you offer insights on why this does not work with this plugin?

**Comment by BenKletzine** [comment]
Just want to verify this is a bug with the plugin, and not mistake on my implementation?

**Comment by DeviaVir** [comment]
@BenKletzine I've had a couple reports on this, so fairly certain this is a bug with the plugin.

**Comment by psalaberria002** [comment]
@BenKletzine Could you print the logs please? What is the error message?

**Comment by BenKletzine** [comment]
Here is the error message 

* gsuite_group_members.someBucket_dev_group_members: Error updating memberships: Error checking hasmember: googleapi: Error 400: Invalid Input: memberKey, invalid, abc@appspot.gserviceaccount.com

**Comment by DeviaVir** [comment]
@BenKletzine this looks like an issue only on the `gsuite_group_members` resource. You can work around this by using `gsuite_group_member` directly while we figure out what the issue is.

**Comment by DeviaVir** [comment]
@psalaberria002 https://github.com/DeviaVir/terraform-provider-gsuite/blob/master/gsuite/resource_group_members.go#L302 it dies on this check, I'm pondering if we should remove the return err after or if we should first check the domain... somehow.
