### ISSUE TITLE
Member Not Found 

### ISSUE THREAD

**Issue by BenKletzine** [DeviaVir/terraform-provider-gsuite#26]
Getting this error when applying terraform. For some reason the individual is appearing twice in the output, fails on uppercase email. Any ideas?

gsuite_group_members.mygroup_group_members: Error updating memberships: Error updating groupMember: googleapi: Error 404: Resource Not Found: memberKey, notFound, Ben.Kletzine@gmail.com

~ module.myModuleName.gsuite_group_members.mygroup_group_members
      member.1406108220.email:  "ben.kletzine@gmail.com" => ""
      member.1406108220.role:   "MEMBER" => ""
      member.1524104041.email:  "" => "Ben.Kletzine@gmail.com"
      member.1524104041.etag:   "" => <computed>
      member.1524104041.kind:   "" => <computed>
      member.1524104041.role:   "" => "MEMBER"
      member.1524104041.status: "" => <computed>
      member.1524104041.type:   "" => <computed>

**Comment by DeviaVir** [comment]
Can you share your .tf code?

**Comment by psalaberria002** [comment]
It looks like it is case sensitive. Does the google api always return emails in lower case? Unfortunately I cannot try it out at the moment.

@BenKletzine as a short term fix try to lower case the email.

**Comment by psalaberria002** [comment]
Which version are you running @BenKletzine ? https://github.com/DeviaVir/terraform-provider-gsuite/releases/tag/v0.1.7 has a fix that seems related to your issue.

**Comment by BenKletzine** [comment]
Ok, I updated to 0.1.7 and now I am getting
* gsuite_group_members.mygroup_group_members: Error updating memberships: Error deleting member: googleapi: Error 404: Resource Not Found: memberKey, notFound

Here is a snippet of the output
-/+ module.myModule.mygroup_members.mygroup_group_members (new resource required)
      id:                       "myGroupEmail@gmail.com" => <computed> (forces new resource)
      group_email:              "myGroupEmail@gmail.com" => "myGroupEmail@gmail.com"
      member.#:                 "12" => "12"
      member.***.email:  "ben.kletzine@gmail.com" => "" (forces new resource)

So it seems the resource not found is null or empty? Looks like the forcing is new. I was at 0.11.2 beforehand.

**Comment by psalaberria002** [comment]
If you change the name of the groupId in the gsuite_group_members resource it will try to delete the old resource, and create a new one. Give it a try with #27

**Comment by BenKletzine** [comment]
Sure I will try when merged
