### ISSUE TITLE
Group got created with user type: USER

### ISSUE THREAD

**Issue by kumarvastav** [DeviaVir/terraform-provider-gsuite#30]
The above issue is seen multiple times, where the group got created through Terraform but the group type populated as USER.
However while creating the group, type isn't defined and thus, it's quite uncertain on the reasons why USER type is used. Due to this, none of the members were given IAM access in GCP projects.

Anyone has any idea on this ? Is there something that we are doing wrong ?

**Comment by DeviaVir** [comment]
Do you mean the member type? As far as I'm aware groups do not have a type (https://godoc.org/google.golang.org/api/admin/directory/v1#Group)
