### ISSUE TITLE
Is compatible with terraform import?

### ISSUE THREAD

**Issue by patrickmorin** [DeviaVir/terraform-provider-gsuite#44]
Hi, thanks a lot for the provider. Just a question: I use this provider for managing my groups and users in my organization, I already have some groups and users and I need to import them in Terraform.
I obtain:
```
Error fetching group. Make sure the group exists: googleapi: Error 403: Not Authorized to access this resource/api, forbidden
```
The group exists and I already create some groups with my service account.
So, is the provider compatible with `terraform import`?

**Comment by patrickmorin** [comment]
Ok, I got it.
Don't know why, but by setting `export GOOGLE_CREDENTIALS="/my/path/key.json` and `export IMPERSONATED_USER_EMAIL="me@mail.com`, all is good

**Comment by DeviaVir** [comment]
Yes, this provider supports import.
