### ISSUE TITLE
Missing mapping for customSchemas

### ISSUE THREAD

**Issue by waeltken** [DeviaVir/terraform-provider-gsuite#45]
Would be great to add support for customSchemas as mentioned in the [AWS Guide for Federated Single Sign-On to AWS Using Google Apps](https://aws.amazon.com/de/blogs/security/how-to-set-up-federated-single-sign-on-to-aws-using-google-apps/) at the end of step 4 and step 7.

**Comment by DeviaVir** [comment]
Is your request covered by this PR? https://github.com/DeviaVir/terraform-provider-gsuite/pull/43

**Comment by waeltken** [comment]
It looks like it. I'll have to try that!

**Comment by DeviaVir** [comment]
Included in latest release https://github.com/DeviaVir/terraform-provider-gsuite/releases/tag/v0.1.14
