### ISSUE TITLE
Data for groups

### ISSUE THREAD

**Issue by innovia** [DeviaVir/terraform-provider-gsuite#49]
is it possible to get a data module that will return the list of members and group info?

I have a need to get the members for a gsuite group to use it in github as the users.

is it something that you can do easily?

**Comment by psalaberria002** [comment]
It should be super easy to implement. Give it a shot.

**Comment by DeviaVir** [comment]
See https://github.com/DeviaVir/terraform-provider-gsuite/blob/master/gsuite/data_user_attributes.go for an example to go off of.
