### ISSUE TITLE
Resource gsuite_user is broken

### ISSUE THREAD

**Issue by Jacob-Thorne** [DeviaVir/terraform-provider-gsuite#55]
When adding a new user with the gsuite_user resoursce terraform apply gives the error:
```
Error: Error applying plan:

1 error(s) occurred:

* gsuite_user.developer: 1 error(s) occurred:

* gsuite_user.developer: Error creating user: googleapi: Error 400: Invalid Input: Bad request for , invalid
```

However, a user does get created although the name values for the user are not created.

Trying to apply the terraform again gives this error:

```
Error: Error applying plan:

1 error(s) occurred:

* gsuite_user.developer: 1 error(s) occurred:

* gsuite_user.developer: Error creating user: googleapi: Error 503: Service unavailable. Please try again, backendError
```

I am using the example from 
https://github.com/DeviaVir/terraform-provider-gsuite/blob/master/examples/admin-user/devteam.tf

Kind regards,
Jacob

**Comment by DeviaVir** [comment]
Looks like a problem specific to posix, if you don't need it you can drop it for now. I'm seeing about making the provider compatible with the API again.

**Comment by DeviaVir** [comment]
Contained in v0.1.17 :+1: 
closing.
