### ISSUE TITLE
How can we use other user properties?

### ISSUE THREAD

**Issue by harpenden** [DeviaVir/terraform-provider-gsuite#62]
Hi,

I would like to use "orgUnitPath" user property https://developers.google.com/admin-sdk/directory/v1/reference/users

Is there a way to use those additional properties?

Thanks!

**Comment by DeviaVir** [comment]
Hello.

You can add this additional property by extending https://github.com/DeviaVir/terraform-provider-gsuite/blob/master/gsuite/resource_user.go further to include what you need.

Hopefully if everyone who needs a specific property adds them we end up with a complete solution one day.

**Comment by DeviaVir** [comment]
@mattsimonsen added the `orgUnitPath` that was requested in this ticket. Will close for now.
