### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by Vasanth2896** [DeviaVir/terraform-provider-gsuite#69]
Hello there,
Please list the resources that are available under this provider.I can't see any providers here.

**Comment by DeviaVir** [comment]
Have you seen https://github.com/DeviaVir/terraform-provider-gsuite/tree/master/examples ?

**Comment by Vasanth2896** [comment]
> Have you seen https://github.com/DeviaVir/terraform-provider-gsuite/tree/master/examples ?

Yes,I have seen it. I want to use the resource Gsuite_users.But please do list the arguements which are present under that resources.

**Comment by drebes** [comment]
In addition to the example, you can find all the supported attributes in the [source code](https://github.com/DeviaVir/terraform-provider-gsuite/blob/master/gsuite/resource_user.go#L32)

**Comment by Vasanth2896** [comment]
Thank you @drebes
