### ISSUE TITLE
Full Name always requires a change in user resource

### ISSUE THREAD

**Issue by psalaberria002** [DeviaVir/terraform-provider-gsuite#71]
<img width="377" alt="Captura de pantalla 2019-06-13 a las 20 56 41" src="https://user-images.githubusercontent.com/2410564/59459766-e04f4d00-8e1d-11e9-9b7e-8466bb618d13.png">

The computed field is being reset to null in every run. Is this a known issue?

**Comment by DeviaVir** [comment]
Fix included in https://github.com/DeviaVir/terraform-provider-gsuite/releases/tag/v0.1.21 - dropping `full_name`
