### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by okgolove** [DeviaVir/terraform-provider-gsuite#88]
Hi @DeviaVir! Thank you for the provider.

It would be great if you created the detailed documentation (like for another Terraform providers).

**Comment by sioncojp** [comment]
I'm currently working on a PR.

**Comment by sioncojp** [comment]
@okgolove @DeviaVir  Please check the updated documentation. 

https://github.com/DeviaVir/terraform-provider-gsuite/tree/master/website/docs

Please check the updated documentation.

If there is no problem, I think that this issue can be closed when https://registry.terraform.io/providers/DeviaVir/gsuite/latest/docs is updated.

**Comment by okgolove** [comment]
Good job, thank you!

**Comment by DeviaVir** [comment]
https://github.com/DeviaVir/terraform-provider-gsuite/releases/tag/v0.1.56
