### ISSUE TITLE
Resource gsuite_user doesn't support existing users (added outside of module usage)

### ISSUE THREAD

**Issue by notshof** [DeviaVir/terraform-provider-gsuite#93]
When a user is created outside of the Terraform module an error 409 occurs which states the entity already exists so you can't add a custom schema.

**Comment by DeviaVir** [comment]
There is already a user schema importer: https://github.com/DeviaVir/terraform-provider-gsuite/blob/master/gsuite/resource_user_schema.go#L232

**Comment by notshof** [comment]
@DeviaVir when you create an account within gsuite manually through the browser/console. And then try to add a custom schema with the Terraform module by using gsuite_user the error

`Error: [ERROR] Error updating user: {"error":{"errors":[{"domain":"global","reason":"duplicate","message":"Entity already exists."}],"code":409,"message":"Entity already exists."}}: googleapi: Error 409: Entity already exists., duplicate`
occurs.
