### ISSUE TITLE
recovery_email issues in v0.1.27

### ISSUE THREAD

**Issue by mikelaramie** [DeviaVir/terraform-provider-gsuite#97]
To open with - thank you for this provider; it's made my life a lot easier for standing up demo environments!

In v0.1.27, I'm having trouble getting the recovery_email field to accept any email address.  I've tried with "none@none.com", my personal gmail account, and the impersonation email address; all 3 return:

```
Error: Error creating user: googleapi: Error 400: Invalid recovery email., invalid

  on 00-User.tf line 23, in resource "gsuite_user" "default-account":
  23: resource "gsuite_user" "default-account" {
```
The user stanza in question was:
```
resource "gsuite_user" "default-account" {
  name = {
    family_name = "User"
    given_name  = "${terraform.workspace}"
  }
  password        = "${random_id.password.hex}"
  primary_email   = "${terraform.workspace}-${random_id.project.hex}@${var.gsuite_domain}"
  recovery_email  = "${var.impersonation_email}"
  recovery_phone  = "+15555551212"
  posix_accounts {
    home_directory = "/home/${terraform.workspace}"
    primary        = true
    gid            = 1001
    uid            = random_integer.uid.result
    shell          = "/bin/bash"
    system_id      = "uid"
    username       = "${terraform.workspace}"
  }
}
```

Any guidance?  Or can I make a PR/FR that recovery_email and recovery_phone become optional attributes vs. required?

I've reverted back to v0.1.24 as a workaround for now.

**Comment by DeviaVir** [comment]
Ah damn, I missed those becoming required. If you don't mind PR'ing I'd be happy to merge and deploy a new version.

**Comment by mikelaramie** [comment]
Sure thing, created PR #98

**Comment by DeviaVir** [comment]
https://github.com/DeviaVir/terraform-provider-gsuite/releases/tag/v0.1.28 released
